### PR TITLE
Fix flappy drain test

### LINKED ISSUE #1317: Node: Flappy drain test
```
TCHANNEL INFO: draining channel ~ { hostPort: '127.0.0.1:53391', reason: 'testdown', count: 7 }
  not ok 3423 unexpected channel[1] peer[0] conn[0]
⨯ immediate drain      operator: fail
      at: eachConn (/home/travis/build/uber/tchannel/node/test/lib/alloc-cluster.js:87:32)
    ...
  not ok 3425 unexpected channel[2] peer[0] conn[0]
    ---
      operator: fail
      at: eachConn (/home/travis/build/uber/tchannel/node/test/lib/alloc-cluster.js:87:32)
    ...
  not ok 3427 unexpected channel[3] peer[0] conn[0]
    ---
      operator: fail
      at: eachConn (/home/travis/build/uber/tchannel/node/test/lib/alloc-cluster.js:87:32)
    ...
```

cc @jcorbin @kriskowal

### PR DESCRIPTION
**Pull request by anson627**
To fix #1317
@jcorbin @Raynos @ShanniLi

### CODE REVIEW

File: node/test/chan_drain.js [hunk 1]
```diff
@@ -739,11 +734,24 @@ function checkFinish(assert, err, cluster, finishCount) {
...
+function waitForConnRemoved(count, cluster, callback) {
+    cluster.channels.forEach(function eachChannel(chan) {
+        var peers = chan.peers.values();
+        peers.forEach(function eachPeer(peer) {
+            peer.on('removeConnection', removed);
+        });
+    });
+
+    function removed() {
+        if (--count === 0) {
```
Comment (jcorbin) [inline node/test/chan_drain.js]: please defensive: `<= 0`

File: node/test/chan_drain.js [hunk 2]
```diff
@@ -739,11 +734,24 @@ function checkFinish(assert, err, cluster, finishCount) {
...
+            callback();
```
Comment (jcorbin) [inline node/test/chan_drain.js]: please explicit null arg

File: node/test/chan_drain.js [hunk 3]
```diff
@@ -739,11 +734,24 @@ function checkFinish(assert, err, cluster, finishCount) {
...
-    }
 
-    if (finishCount <= 0) {
         assert.end();
     }
 
     return finishCount;
 }
+
+function waitForConnRemoved(count, cluster, callback) {
```
Comment (jcorbin) [inline node/test/chan_drain.js]: is there any chance we could just compute the count rather than statically set it? maybe something like:
```
count = 1
  for each chan
    for each peer:
      count += peer.connection.length
      peer.on(..., removed)
removed() // this is to match the "1 to start" above, and ensures that we won't erroneously fire the callback while still iterating chan/peers
```

**Comment by jcorbin** [comment]
great catch, some comments for improvement

File: node/test/chan_drain.js (hunk 3 above)
Comment (anson627) [inline node/test/chan_drain.js]: I actually tried it first, the last two test cases timeout, because only 2 out of 6 connections are expected to be removed.

Comment (jcorbin) [inline node/test/chan_drain.js]: ahh okay, that makes sense I suppose, never mind then :-)

**Comment by jcorbin** [comment]
lgtm :+1:
