### PR TITLE
Ensure endpoint-handler always builds response

### LINKED ISSUE #875: Uncaught exception: Cannot set property 'as' of undefined
Received uncaught exception from tchannel while staging a new build on a standalone 1k-node Ringpop cluster.

I'm running tchannel 2.0.5.

```
"stack":"TypeError: Cannot set property 'as' of undefined
    at handleThriftResponse (node_modules/tchannel/as/thrift.js:164:28)
    at onCallback (node_modules/ringpop/server/index.js:173:9)
    at handlePing (node_modules/ringpop/server/ping-handler.js:36:5)
    at handleIt (node_modules/ringpop/server/index.js:110:9)
    at TChannelEndpointHandler.handleThriftRequest (node_modules/tchannel/as/thrift.js:122:9)
    at onArg23 (node_modules/tchannel/request-handler.js:57:34)
    at compatCall (node_modules/tchannel/streaming_in_request.js:76:9)
    at zalgoSafe (node_modules/dezalgo/dezalgo.js:20:10)
    at done (node_modules/tchannel/node_modules/run-parallel/index.js:18:15)
    at signalReady (node_modules/tchannel/node_modules/ready-signal/index.js:21:26)
    at StreamArg.finish node_modules/tchannel/argstream.js:263:9)
    at StreamArg.emit (events.js:117:20)
    at node_modules/tchannel/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickDomainCallback (node.js:463:13)”,
"message":"Cannot set property 'as' of undefined"
```

### PR DESCRIPTION
**Pull request by Raynos**
The endpoint-handler was being non-deterministic and
either building the response for you or not.

It should always build the response.

This fixes #875

r: @wolski @kriskowal @shannili

### CODE REVIEW

**Comment by ShanniLi** [comment]
lgtm

File: node/request-handler.js [hunk 1]
```diff
@@ -54,7 +54,8 @@ RequestCallbackHandler.prototype.handleRequest = function handleRequest(req, bui
     var res;
     if (req.streamed) {
         req.withArg23(function onArg23(err, arg2, arg3) {
-            return self.callback.call(self.thisp, req, buildResponse, arg2, arg3);
+            res = buildResponse({streamed: false});
+            return self.callback.call(self.thisp, req, res, arg2, arg3);
```
Comment (kriskowal) [inline node/request-handler.js]: Good catch.

**Comment by kriskowal** [comment]
Land it. This impacted Ringpop, right?

**Comment by jwolski** [comment]
wewt. can you fine people cut a tag with this?

**Comment by ShanniLi** [comment]
@jwolski cut the new tag: 2.0.6
